---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.15

jobs:
  build:
    executor: golang

    steps:
    - checkout
    - run: sudo apt-get install -y libpam0g-dev
    - run: go mod download
    - run: make style
    - run: make
    - store_artifacts:
        path: bin

workflows:
  version: 2
  build:
    jobs:
    - build
