---
version: 2

jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/nDenerserve/SmartPi

    steps:
    - checkout
    - run: sudo apt-get install -y libpam0g-dev
    - run: make style
    - run: make
    - store_artifacts:
        path: bin

workflows:
  version: 2
  build:
    jobs:
    - build
